src/models/News.php
<?php
namespace yii2press\news\models;


use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * Class News
 * @package yii2press\models
 *
 * @property integer $id
 * @property string  $slug
 * @property string  $title
 * @property integer $status
 * @property integer $category_id
 * @property string  $description
 * @property string  $content
 * @property string  $purify
 * @property string  $image
 * @property integer $use_image
 * @property string  $image_text
 * @property string  $video
 * @property integer $use_video
 * @property string  $source_url
 * @property integer $rss
 * @property integer $main
 * @property integer $important
 * @property integer $advert
 * @property string  $created
 * @property string  $published
 * @property string  $modify
 * @property string  $unpublished
 * @property integer $author_id
 * @property integer $redactor_id
 * @property integer $publisher_id
 * @property integer $views
 * @property integer $comments
 * @property string  $gallery_json
 * @property string  $picture_story
 * @property string  $meta_title
 * @property string  $meta_keywords
 * @property string  $meta_description
 *
 * @property Category $category
 */
class News extends \yii\db\ActiveRecord
{
    /** Скрыто */
    const STATUS_UNPUBLISHED = 0;

    /** Доступно только по прямой ссылке, не выводится в лентах */
    const STATUS_PUBLISHED_PRIVATE = 10;

    /** Выводится в ленте категории */
    const STATUS_PUBLISHED_PUBLIC = 20;

    /** Выводится в ленте на главной */
    const STATUS_PUBLISHED_INDEX = 30;

    public static function getStatusList()
    {
        return [
            self::STATUS_PUBLISHED_INDEX => 'На главной',
            self::STATUS_PUBLISHED_PUBLIC => 'В категории',
            self::STATUS_PUBLISHED_PRIVATE => 'Приватно',
            self::STATUS_UNPUBLISHED => 'Скрыто',
        ];
    }

    public $modelMap;

    public $deniedCategories = [9, 10, 11];

    public function rules()
    {
        return [
            [['title', 'slug', 'description', 'content', 'purify', 'image', 'image_text', 'video', 'source_url', 'gallery_json', 'picture_story', 'meta_title', 'meta_keywords', 'meta_description'], 'string'],
            [['status', 'category_id', 'use_image', 'use_video', 'rss', 'main', 'important', 'advert', 'author_id', 'redactor_id', 'publisher_id', 'views', 'comments'], 'integer'],
            [['created', 'published', 'modify', 'unpublished', 'tagValues', 'publisher_id' ], 'safe'],

            [['title', 'description', 'content'], 'required'],
            [['title', 'slug'], 'unique'],
            [['slug', 'description', 'image_text', 'meta_title', 'meta_keywords', 'meta_description'], 'string', 'max' => 255],
            [['use_image', 'use_video', 'main', 'important', 'advert',  'comments', 'views', 'comments'], 'default', 'value' => 0],
            [['status', 'rss', ], 'default', 'value' => 0],

            [['status'], 'default', 'value' => self::STATUS_PUBLISHED_INDEX, 'on' => ['publication']],
            [['rss'], 'default', 'value' => 1, 'on' => ['publication']],
            [['title'], 'string', 'max' => 180, 'on' => ['publication']],

            ['category_id', 'exist', 'targetClass' => 'yii2press\\news\\models\\Category', 'targetAttribute'=>'id' ]
            

        ];
    }

    public function beforeValidate()
    {
        $this->purify = $this->content;
        return parent::beforeValidate();
    }

    public function beforeSave($insert)
    {
        $this->meta_title = $this->title;
        $this->meta_description = $this->description;
        return parent::beforeSave($insert);
    }

    public function behaviors()
    {
        return [
            'slug' => [
                'class' => '\\yii\\behaviors\\SluggableBehavior',
                'attribute' => 'title',
                'immutable' => true,
            ],
            'timestamp' => [
                'class' => '\\yii\\behaviors\\TimestampBehavior',
                'attributes' => [

                    parent::EVENT_BEFORE_INSERT => ['modify', 'created'],
                    parent::EVENT_BEFORE_UPDATE => ['modify'],
                ],
                'value' => new Expression('NOW()'),
            ],
            'purify' => [
                'class' => '\\yii2press\\core\\behaviors\\PurifierBehavior',
                'textAttributes' => [
                    parent::EVENT_BEFORE_INSERT => ['title', 'description', 'meta_title', 'meta_keywords', 'meta_description', 'purify', 'source_url'],
                    parent::EVENT_BEFORE_UPDATE => ['title', 'description', 'meta_title', 'meta_keywords', 'meta_description', 'purify', 'source_url'],
                ],
                'attributes' => [
                    parent::EVENT_BEFORE_INSERT => ['content'],
                    parent::EVENT_BEFORE_UPDATE => ['content'],
                ],
                'purifierOptions' => [
                    'content' => [
                        'HTML.Allowed'         => 'strong, em, ul, ol, li, img[src], a[href], p, span, h2, h3, h4, h5, h6',
                        'HTML.Trusted'         => TRUE,
                        'HTML.TidyAdd'         => [],
                        'HTML.TidyLevel'       => 'heavy',
                        'HTML.SafeIframe'      => true,
                        'URI.SafeIframeRegexp' => '%^http://(www.youtube(?:-nocookie)?.com/embed/|player.vimeo.com/video/)%',
                    ]
                ]
            ],
            'blameable' => [
                'class' => '\\yii\\behaviors\\BlameableBehavior',
                'attributes' => [
                    parent::EVENT_BEFORE_INSERT => ['author_id', 'publisher_id', 'redactor_id'],
                    parent::EVENT_BEFORE_UPDATE => ['redactor_id'],
                ],
            ],
            'taggable' => [
                'class' => '\\creocoder\\taggable\\TaggableBehavior'
            ],
            'gallery' => [
                'class' => 'yii2press\\jgmanager\\behaviors\\GalleryBehavior',
                'attribute' => 'picture_story',
            ]

        ];
    }

    public function init()
    {
        $this->modelMap = Yii::$app->getModule('news')->modelMap;
        return parent::init();
    }

    public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL,
        ];
    }

    /**
     * @return \app\modules\news\models\NewsQuery | \yii2press\news\models\NewsQuery | \yii\db\ActiveQuery
     */
    public static function find()
    {
        $model = Yii::$app->getModule('news')->modelMap['NewsQuery'];
        return new $model(get_called_class());
    }

    public static function tableName()
    {
        return '{{%news_item}}';
    }

    public function isDenied()
    {
        $post = (new \DateTime($this->published))->modify('+48 hour');
        $now = (new \DateTime());
        if (in_array($this->category_id, $this->deniedCategories) && $post > $now && !Yii::$app->user->can('subscriber')) {
            return true;
        }
        return false;
    }

    /**
     * @return \yii\db\ActiveQuery Возвращает категорию публикации
     */
    public function getCategory()
    {
        return $this->hasOne($this->modelMap['Category'], ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery Возвращает создателя публикации
     */
    public function getAuthor()
    {
        return $this->hasOne($this->modelMap['User'], ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery Возвращает последнего редактора публикации
     */
    public function getRedactor()
    {
        return $this->hasOne($this->modelMap['User'], ['id' => 'redactor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery Возвращает автора публикации
     */
    public function getPublisher()
    {
        return $this->hasOne($this->modelMap['User'], ['id' => 'publisher_id']);
    }

    /**
     * @return array Список доступных авторов
     * @throws \yii\base\InvalidConfigException
     */
    public function getAllowedPublishers()
    {
        /** @var \dektrium\user\models\User $model */
        $model = Yii::createObject($this->modelMap['User']);
        $model = $model::find()->where(['role' => ['redactor', 'admin', 'manager', 'superadmin']])->asArray()->all();
        return \yii\helpers\ArrayHelper::map($model, 'id', 'username');
    }

    /**
     * @return \yii\db\ActiveQuery Возвращает теги публикации
     */
    public function getTags()
    {
        return $this->hasMany($this->modelMap['Tag'], ['id' => 'tag_id'])->viaTable('{{%news_tag_assn}}', ['news_id' => 'id']);
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'slug' => 'Slug',
            'title' => 'Заголовок',
            'status' => 'Видимость',
            'category_id' => 'Категория',
            'description' => 'Описание',
            'content' => 'Содержание',
            'purify' => 'Purify',
            'image' => 'Изображение',
            'use_image' => 'Исп. изобр.',
            'image_text' => 'Подпись к изобр.',
            'video' => 'Video',
            'use_video' => 'Исп. видео',
            'source_url' => 'URL источника',
            'rss' => 'Rss',
            'main' => 'Главная',
            'important' => 'Важная',
            'advert' => 'Реклама',
            'created' => 'Создано',
            'published' => 'Опубликованно',
            'modify' => 'Отредактировано',
            'unpublished' => 'Скрыто',
            'author_id' => 'Автор',
            'redactor_id' => 'Редактор',
            'publisher_id' => 'Автор публ.',
            'views' => 'Просмотры',
            'comments' => 'Комментарии',
            'gallery_json' => 'Галлерея',
            'picture_story' => 'Галлерея',
            'tagValues' => 'Теги',
            'meta_title' => 'SEO title',
            'meta_keywords' => 'SEO keywords',
            'meta_description' => 'SEO description',
        ];
    }
} 

src/views/admin/news/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<div class="news-form">

    <?php $form = ActiveForm::begin([
        'enableAjaxValidation'   => true,
        'enableClientValidation' => true
    ]);
    echo $form->errorSummary($model, ['class' => 'bg-danger', 'style' => 'padding: 10px; margin-bottom: 10px;' ]);

    echo \yii\bootstrap\Tabs::widget([
        'encodeLabels' => false,
        'items' => [
            [
                'label' => '<i class="fa fa-newspaper-o"></i> <br> Основное  ',
                'linkOptions' => ['class' => 'btn btn-md btn-flat', 'title' => 'Основное'],
                'options' => ['style' => 'padding-top: 15px'],
                'content' => $this->render('_form_prop_main', ['model' => $model, 'form' => $form]),
            ],
            [
                'label' => '<i class="fa fa-wrench"></i> <br> Дополнительно',
                'linkOptions' => ['class' => 'btn btn-md btn-flat', 'title' => 'Дополнительно'],
                'options' => ['style' => 'padding-top: 15px'],
                'content' => $this->render('_form_prop_extra', ['model' => $model, 'form' => $form])
            ],
            [
                'label' => '<i class="fa fa-globe"></i> <br> SEO',
                'linkOptions' => ['class' => 'btn btn-md btn-flat', 'title' => 'SEO оптимизация'],
                'options' => ['style' => 'padding-top: 15px'],
                'content' => $this->render('_form_prop_seo', ['model' => $model, 'form' => $form])
            ],
        ]
    ]);
    ?>
    <div class="form-group" style="margin-top: 15px;">
        <?= Html::submitButton('<i class="fa fa-check"></i>&nbsp;Сохранить', ['class' =>'btn btn-success']) ?>
        <?= Html::a('<i class="fa fa-ban"></i>&nbsp;Отмена', ['news-index'], ['class' =>'btn btn-link']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

src/views/admin/news/_form_prop_extra.php
<?php
/**
 * @var \yii\web\View $this
 * @var $form \yii\widgets\ActiveForm
 */
?>
<div class="row">
    <div class="col-xs-10"><?= $form->field($model, 'video')->textarea(['rows' => 3]) ?></div>
    <div class="col-xs-2"><?=\yii\helpers\Html::activeCheckbox($model, 'use_video')?> </div>
</div>

<?= \yii2press\jgmanager\widgets\Input::widget(['model'=>$model, 'attribute'=>'gallery']) ?>

src/views/admin/news/_form_prop_main.php
<?php
/**
 * @var \yii\web\View $this
 * @var \yii2press\news\models\News $model
 */
?>

<div class="row">

    <div class="col-xs-12 col-md-8">
        <?= $form->field($model, 'title')->textInput(['maxlength' => 255]) ?>
        <?= $form->field($model, 'description')->textarea(['rows'=>6]) ?>
        <?php
        $bBundle = Yii::$app->assetManager->getBundle('app\assets\backend\BackendBundle');
        echo \himiklab\ckeditor\CKEditor::widget([
            'model' => $model,
            'attribute' => 'content',
            'useBrowserSpellChecker' => true,
            'editorOptions' => [
                'height' => '400px',
                'customConfig' => $bBundle->baseUrl . '/ckeditor/config.ckeditor.js',
                'filebrowserBrowseUrl' => '/elfinder/manager',
            ]
        ]);
        ?>

        <br/>
        <?= $form->field($model, 'tagValues')->widget('\\dosamigos\\selectize\\SelectizeTextInput', [
            'loadUrl' => ['tag-list'],
            'clientOptions' => [
                'plugins' => ['remove_button'],
                'valueField' => 'name',
                'labelField' => 'name',
                'searchField' => ['name'],
                'create' => true,
                'maxItems' => 6
            ],]); ?>

    </div>

    <div class="col-xs-12 col-md-4">

        <div class="panel panel-default">
            <div class="panel-heading">Настройки видимости</div>
            <div class="panel-body">
                <?= $form->field($model, 'category_id')->dropDownList(\yii2press\news\models\Category::getList()) ?>
                <?= $form->field($model, 'status')->dropDownList($model::getStatusList())?>

                <div class="form-group field-news-published">
                    <label for="news-published">Дата</label>
                    <?= \kartik\datetime\DateTimePicker::widget([
                        'model' => $model,
                        'attribute' => 'published',
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'yyyy-mm-dd hh:ii'
                        ]
                    ]) ?>
                </div>

                <?php if(!$model->isNewRecord) : ?>
                <?= $form->field($model, 'publisher_id')->dropDownList($model->allowedPublishers) ?>
                <?php endif; ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Изображение</div>
            <div class="panel-body">
                <?= \mihaildev\elfinder\InputFile::widget([
                    'model' => $model,
                    'attribute' => 'image',
                    'buttonName'    => 'Загрузить',
                    'language'      => 'ru',
                    'controller'    => 'elfinder', // вставляем название контроллера, по умолчанию равен elfinder
                    'filter'        => 'image',    // фильтр файлов, можно задать массив фильтров https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#wiki-onlyMimes
                    'template'      => '<div class="input-group">{input}<span class="input-group-btn">{button}</span> </div>',
                    'options'       => [
                        'class' => 'form-control',
                        'onchange' => "$('#news-img-preview').attr('src', this.value);"
                    ],
                    'buttonOptions' => ['class' => 'btn btn-default'],
                    'multiple'      => false      // возможность выбора нескольких файлов
                ]); ?>
                <?= $form->field($model, 'use_image', ['options' => ['style'=>'margin-top:15px;']])->checkbox(['label' => 'Выводить в ленте']) ?>

                <img id='news-img-preview' src="<?=$model->image?>" alt="" style="display: block; width: 100%;"/>

                <?= $form->field($model, 'image_text')->textarea(['rows'=>2]); ?>

            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">Дополнительно</div>
            <div class="panel-body">
                <?= $form->field($model, 'main')->checkbox(['labelOptions' => ['class'=>'checkbox-inline']]) ?>
                <?= $form->field($model, 'important')->checkbox(['labelOptions' => ['class'=>'checkbox-inline']]) ?>
                <?= $form->field($model, 'rss')->checkbox(['labelOptions' => ['class'=>'checkbox-inline']]) ?>
                <?= $form->field($model, 'advert')->checkbox(['labelOptions' => ['class'=>'checkbox-inline']]) ?>
                <?=  $form->field($model, 'source_url')->textInput() ?>
            </div>
        </div>

    </div>
</div>

src/views/admin/news/_form_prop_seo.php
<?= $form->field($model, 'slug')->textInput(['maxlength' => 255]) ?>
<?= $form->field($model, 'meta_title')->textInput(['maxlength' => 255]) ?>
<?= $form->field($model, 'meta_keywords')->textInput(['maxlength' => 255]) ?>
<?= $form->field($model, 'meta_description')->textarea() ?>

src/views/admin/news/_search.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii2press\news\models\Category;
?>
<div class="box box-info collapsed-box box-solid">
    <div class="box-header with-border">
        <h3 class="box-title">Расширенный поиск</h3>
        <div class="box-tools pull-right">
            <button data-widget="collapse" class="btn btn-box-tool"><i class="fa fa-plus"></i></button>
        </div><!-- /.box-tools -->
    </div><!-- /.box-header -->
    <div class="box-body">
        <?php $form = ActiveForm::begin([
        'action' => ['news-index'],
        'method' => 'get',
        //'enableAjaxValidation'   => true,
        //'enableClientValidation' => true
        ]);
        ?>

        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <?= $form->field($model, 'category_id')->dropDownList(Category::getList()) ?>
                </div>
                <div class="form-group">
                    <label class="control-label"> Период создания</label>
                    <?= \kartik\date\DatePicker::widget([
                        'model' => $model,
                        'attribute' => 'published_from',
                        'attribute2' => 'published_to',
                        'type' => \kartik\date\DatePicker::TYPE_RANGE,
                        'separator' => 'по',
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'yyyy-mm-dd'
                        ]
                    ]) ?>
                </div>
                <?= $form->field($model, 'title')->textInput()?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'important')->checkbox() ?>
            </div>
        </div>


        <div class="form-group">
            <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
            <?= Html::resetButton('Сбросить', ['class' => 'btn btn-danger', 'onclick'=>"document.getElementById('news-search').reset()"]) ?>

        </div>
        <?php ActiveForm::end(); ?>
        <?php ?>
    </div><!-- /.box-body -->
</div>

src/views/admin/news/create.php
<?php
/**
 * View добавления новой новости
 * -------------------------------------------------
 * @var \yii\web\View $this
 * @var \yii2press\news\models\News
 */
$this->title = 'Модуль новостей';
$this->params['breadcrumbs'][] = ['label'=> 'Новости', 'url' => ['/news/admin/news-index']];
$this->params['breadcrumbs'][] = ['label'=> 'Создать'];
?>

<div class="row">
    <div class="col-xs-12">
        <?= $this->render('/admin/_menu') ?>
    </div>
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header"> <h5 class="box-title"> Добавить новость </h5> </div>
            <div class="box-body">
                <?= $this->render('_form', ['model' => $model]); ?>
            </div>
        </div>
    </div>
</div>

src/views/admin/news/index.php
<?php
/**
 * Список, фильтрация, поиск по новостям
 * -------------------------------------------------------------
 * @var \yii\web\View $this
 * @var \yii2press\news\models\Category $model
 */
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii2press\news\models\Category;

$this->title = 'Модуль новостей';
$this->params['breadcrumbs'] = ['Новости'];
?>

<div class="row">
    <div class="col-xs-12">
        <?= $this->render('/admin/_menu') ?>
    </div>
    <div class="col-xs-12">
        <?= $this->render('_search', ['model' => $searchModel]) ?>
        <div class="box box-primary">
            <div class="box-header"> <h4 class=""> Список новостей </h4> </div>
            <div class="box-body category-index">
                <?php Pjax::begin() ?>
                <?= \yii\grid\GridView::widget([
                    'dataProvider' => $dataProvider,
                    'filterModel' => $searchModel,
                    'layout' => '{summary}<div class="table-responsive">{items}</div>{pager}',
                    'rowOptions' => function ($model, $key, $index, $grid){
                        /** @var \yii2press\news\models\News $model */
                        $class = [];
                        if ($model->status==$model::STATUS_UNPUBLISHED || $model->status==$model::STATUS_PUBLISHED_PRIVATE) {
                            Html::addCssClass($class, 'text-muted');
                        } elseif ($model->main==1 || $model->important==1) {
                            Html::addCssClass($class, 'text-danger');
                        }
                        return $class;
                    },
                    'columns' => [
                        ['class' => 'yii\grid\DataColumn', 'attribute' => 'id', 'options' => ['style' => 'width: 80px']],
                        [
                            'class' => 'yii\grid\DataColumn',
                            'attribute' => 'published',
                            'options' => ['style' => 'width: 120px'],
                            'value' => function($data) {
                                return (new DateTime($data->published))->format("d.m H:i");
                            },
                            'filter' => \kartik\date\DatePicker::widget([
                                'model' => $searchModel,
                                'attribute' => 'published',
                                'value' => date("Y-m-d"),
                                'type' => 1,

                                'pluginOptions' => [
                                    'autoclose'=>true,
                                    'format' => 'yyyy-mm-dd'
                                ]
                            ]),


                        ],
                        [
                            'class' => 'yii\grid\DataColumn',
                            'attribute' => 'category_id',
                            'value'=>'category.name',
                            'filter' => Html::activeDropDownList($searchModel, 'category_id', Category::getList(), ['class' => 'form-control'])
                        ],
                        ['class' => 'yii\grid\DataColumn', 'attribute' => 'title', 'format' => 'raw', 'value' => function($data){
                            $type = '';
                            $type .= $data->video ? "<i class='fa fa-video-camera'></i> &nbsp;" : '';
                            $type .= $data->gallery_json ? "<i class='fa fa-camera'></i> &nbsp;" : '';
                            return $data->title.Html::tag('div',$type);
                        }],
                        [
                            'class' => 'yii\grid\DataColumn',
                            'header' => 'Редактор / Автор',
                            'format' => 'raw',
                            'value' => function($data) {
                                return $data->redactor->username .' / '. $data->author->username;
                            }
                        ],

                        [
                            'class' => 'yii\grid\DataColumn',
                            'format' => 'raw',
                            'options' => ['style' => 'width: 12px'],
                            'value'=>function ($data) {
                                $out = $data->main ? Html::tag('div', 'главная',['class'=>'label bg-red pull-right']) : '';
                                $out .= $data->important ? Html::tag('div', 'важная',['class'=>'label bg-yellow pull-right']) : '';
                                $out .= $data->advert ? Html::tag('div', 'реклама',['class'=>'label bg-green pull-right']) : '';
                                return $out;
                            },

                        ],
                        [
                            'class' => 'yii\grid\DataColumn',
                            'label' => 'Пр-ы',
                            'options' => ['style' => 'width: 20px'],
                            'attribute' => 'views',
                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'template' => '{update}{public-view}',
                            'options' => [
                                'style' => 'width: 100px',
                            ],
                            'buttons' => [
                                'update' => function ($url, $model) {
                                    return Html::a(
                                        '<span class="fa fa-pencil"></span>',
                                        Url::to(['/news/admin/news-update', 'id' => $model->id]),
                                        ['class' => 'btn btn-sm btn-primary btn-flat']);
                                },
                                'public-view' => function($url, $model) {
                                    return Html::a(
                                        '<span class="fa fa-play"></span>',
                                        Url::to(['/news/default/view', 'id' => $model->id]),
                                        ['class' => 'btn btn-sm btn-default btn-flat', 'target' => '_blank']
                                    );
                                }
                            ]
                        ],
                    ],
                ]); ?>
                <?php Pjax::end() ?>
            </div>
        </div>
    </div>
</div>

src/views/admin/news/update.php
<?php
/**
 * View редактирования новости
 * -------------------------------------------------------------
 * @var \yii\web\View $this
 * @var \yii2press\news\models\News
 */
$this->title = 'Модуль новостей';
$this->params['breadcrumbs'][] = ['label'=> 'Новости', 'url' => ['/news/admin/news-index']];
$this->params['breadcrumbs'][] = ['label'=> 'Редактировать'];
?>

<div class="row">
    <div class="col-xs-12">
        <?= $this->render('/admin/_menu') ?>
    </div>
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header"> <h5 class="box-title"> Редактировать новость </h5> </div>
            <div class="box-body">
                <?= $this->render('_form', ['model' => $model]); ?>
            </div>
        </div>
    </div>
</div>